# Generated by Django 3.1.4 on 2020-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
